### PR TITLE
Bump checkout and setup-go in actions

### PR DESCRIPTION
**Pull request by tgragnato**
- [chore(ci): bump actions/checkout from 3 to 4](https://github.com/immobiliare/inca/commit/48e8796286f01839101c745592a0d9572d66d984)
- [chore(ci): bump actions/setup-go from 4 to 5](https://github.com/immobiliare/inca/commit/bf364f962dfed67962ee467cb7a2a2f6601b927e)

### CODE REVIEW

**Review by JellyBellyDev — APPROVED** [review]
LGTM 👍

**Comment by JellyBellyDev** [comment]
@tgragnato why you continue to work on your fork? :)

**Comment by tgragnato** [comment]
> @tgragnato why you continue to work on your fork? :)

Mainly because here I'm missing a custom dependabot configuration for a completely automatic dependency management.

https://github.com/tgragnato/inca/blob/main/.github/dependabot.yml

**Comment by JellyBellyDev** [comment]
feel free to best configure this repo! ;)

**Pull request merged**
