### PR TITLE
feat(provider): support for the HTTP-01 challenge

### LINKED ISSUE #18: HTTP-01 challenge / Enhance the capabilities of the Let's Encrypt provider
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

The HTTP-01 challenge is designed to verify that the entity requesting a certificate has control over the domain. By successfully completing this challenge, the software can demonstrate to Let's Encrypt that it has the necessary control over the specified domain, ensuring the security and authenticity of the certificate issuance process.

Different environments and configurations may require different challenge types. Supporting the HTTP-01 challenge provides flexibility for users who may prefer or need this specific challenge over DNS-01 based on their infrastructure and security requirements.

### PR DESCRIPTION
**Pull request by tgragnato**
closes #18 

The functionality is designed to activate by setting "**webroot**" in the provider's configuration. It is the responsibility of system administrators to route HTTP traffic for the prefix `/.well-known/acme-challenge/` to Inca.

TODO: There are no unit tests for the providers, and this is partially correct as we do not want to rewrite tests that cover the features provided by the library we are using (_lego_). However, it would be very helpful to start introducing **_tests for the glue code_**.

For now, the introduced functionality is trivial, and it seems possible to safely introduce it without implementing unit testing beforehand for this portion of the code.

NB: Static serving is heavily dependent on the `WORKDIR /tmp` Docker directive; everything breaks down in different environments.

### CODE REVIEW

**Review by JellyBellyDev — CHANGES_REQUESTED** [review]
Maybe we should add a little bit of documentation on this feat?

**Comment by tgragnato** [comment]
> Maybe we should add a little bit of documentation on this feat?

+1. A complete documentation is missing for basically everything regarding the configuration yaml (not just this feature).

We could start documenting this and expand/recover a description of everything that's missing, starting from a basic skeleton.

What could be a good place for the docs?

**Review by JellyBellyDev — APPROVED** [review]
LGTM 👍

**Comment by tgragnato** [comment]
> > +1. A complete documentation is missing for basically everything regarding operations and the configuration yaml (not just this feature).
> > We could start documenting this and expand/recover a description of everything that's missing, starting from a basic skeleton.
> 
> Ok no problem. I suggest to do this in new PR! ;)
> 
> > What could be a good place for the docs?
> 
> One dir `documentation` at the root of repo with inside all file md and in the file readme the special toc for docs?

https://github.com/immobiliare/inca/issues/31

**Pull request merged**
